const algoMutatingMoreInfo = `These works explore AI as a medium for new forms of digital writing — a process the artists call Ultra Large Digital Narratives (ULDN). The resulting animated, interactive worlds weave together organic creatures and fantastic machines, with fragments of story emerging across the visual display.\n\nDr. Jason Nelson and Dr. Alinta Krauth (Center for Digital Narrative / EphemerLab) move well beyond simple "prompt and generate" methods: each piece is built from hundreds of individual image fragments, stitched into layered visual and narrative concepts that exploit AI's painterly and anticipatory possibilities.`;

export const aiArtVideos = [
  {
    id: 'oMngEHXiGqg',
    title: 'AlgoMutating Digital Creatures — Ultra Large Digital Narrative Series Vid5',
    artist: 'Jason Nelson & Alinta Krauth',
    description: 'This video is part of the Ultra Large Digital Narrative Series, showcasing the fascinating world of AlgoMutating Digital Creatures',
    moreInfo: algoMutatingMoreInfo,
    uldn: true,
  },
  {
    id: 'pGXdy8JAFew',
    title: 'AlgoMutating Digital Creatures — Ultra Large Digital Narrative Series Vid2',
    artist: 'Jason Nelson & Alinta Krauth',
    description: 'This video is part of the Ultra Large Digital Narrative Series, featuring the intriguing world of AlgoMutating Digital Creatures',
    moreInfo: algoMutatingMoreInfo,
    uldn: true,
  },
  {
    id: 'NKKS769trzA',
    title: 'AlgoMutating Digital Creatures — Ultra Large Digital Narrative Series Vid3',
    artist: 'Jason Nelson & Alinta Krauth',
    description: 'This video is part of the Ultra Large Digital Narrative Series, showcasing the fascinating world of AlgoMutating Digital Creatures.',
    moreInfo: algoMutatingMoreInfo,
    uldn: true,
  },
  {
    id: '8vYwobYn0yc',
    title: 'AlgoMutating Digital Creatures — Ultra Large Digital Narrative Series Vid1',
    artist: 'Jason Nelson & Alinta Krauth',
    description: 'This video is part of the Ultra Large Digital Narrative Series, featuring the intriguing world of AlgoMutating Digital Creatures.',
    moreInfo: algoMutatingMoreInfo,
    uldn: true,
  },
  {
    id: 'AA0XkX6sTKI',
    title: 'AlgoMutating Digital Creatures — Ultra Large Digital Narrative Series Vid6',
    artist: 'Jason Nelson & Alinta Krauth',
    description: 'This video is part of the Ultra Large Digital Narrative Series, showcasing the fascinating world of AlgoMutating Digital Creatures.',
    moreInfo: algoMutatingMoreInfo,
    uldn: true,
  },
  {
    id: 'UmQG7r9tYTI',
    title: 'AI-collaborative art-treehouse',
    artist: 'Jason Nelson & Alinta Krauth',
    description: 'An AI-collaborative digital artwork exploring the intersection of machine creativity and organic structure.',
    moreInfo: algoMutatingMoreInfo,
    uldn: true,
  },
  {
    id: '1139698598',
    platform: 'vimeo',
    title: 'Can you Copium?',
    artist: 'David Jhave Johnston',
    description: `A weekend project exploring AI-generated memes created with Gemini 3, Nano Banana Pro, and Veo3 — blending high-level academic concepts with low-level internet culture aesthetics. Produced at the University of Bergen's Center for Digital Narrative.`,
    mute: false,
  },
  {
    id: 'M5YsS2ohuE8',
    title: 'Digital Art, Creativity and AI - The More Than Meets AI Exhibition',
    artist: 'Center for Digital Narrative (CDN)',
    description: `Step inside "More Than Meets AI" — an international art exhibition where five participating artists share how they're incorporating AI in their practice. They discuss their worries, and why "human agency" still matters.`,
    mute: false,
  },
];
